"""initial

Revision ID: 04734245437f
Revises: 
Create Date: 2026-04-20 13:06:28.100101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04734245437f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Text(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_messages', schema=None) as batch_op:
        batch_op.create_index('ix_agent_messages_session_id', ['session_id'], unique=False)

    op.create_table('user_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Text(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_messages', schema=None) as batch_op:
        batch_op.create_index('ix_user_messages_session_id', ['session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_messages', schema=None) as batch_op:
        batch_op.drop_index('ix_user_messages_session_id')

    op.drop_table('user_messages')
    with op.batch_alter_table('agent_messages', schema=None) as batch_op:
        batch_op.drop_index('ix_agent_messages_session_id')

    op.drop_table('agent_messages')
    # ### end Alembic commands ###
