"""add user memories

Revision ID: 292a47f8f8d7
Revises: 5ca54f1be44f
Create Date: 2026-04-21 09:54:37.766711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from database.vec_ddl import (
    downgrade_user_memories_vec,
    upgrade_user_memories_vec,
)
from settings import settings


# revision identifiers, used by Alembic.
revision: str = '292a47f8f8d7'
down_revision: Union[str, Sequence[str], None] = '5ca54f1be44f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_memories',
    sa.Column('rowid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('metadata', sa.LargeBinary(), nullable=True),
    sa.Column('text_embedding', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('rowid')
    )
    # ### end Alembic commands ###
    upgrade_user_memories_vec(dim=settings.embedding_dim)


def downgrade() -> None:
    """Downgrade schema."""
    downgrade_user_memories_vec()
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_memories')
    # ### end Alembic commands ###
