"""add checkpointer tables

Revision ID: 5ca54f1be44f
Revises: 04734245437f
Create Date: 2026-04-21 04:51:21.844966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ca54f1be44f'
down_revision: Union[str, Sequence[str], None] = '04734245437f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checkpoints',
    sa.Column('thread_id', sa.Text(), nullable=False),
    sa.Column('checkpoint_ns', sa.Text(), server_default='', nullable=False),
    sa.Column('checkpoint_id', sa.Text(), nullable=False),
    sa.Column('parent_checkpoint_id', sa.Text(), nullable=True),
    sa.Column('type', sa.Text(), nullable=True),
    sa.Column('checkpoint', sa.LargeBinary(), nullable=True),
    sa.Column('metadata', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'checkpoint_id'),
    if_not_exists=True
    )
    op.create_table('writes',
    sa.Column('thread_id', sa.Text(), nullable=False),
    sa.Column('checkpoint_ns', sa.Text(), server_default='', nullable=False),
    sa.Column('checkpoint_id', sa.Text(), nullable=False),
    sa.Column('task_id', sa.Text(), nullable=False),
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('channel', sa.Text(), nullable=False),
    sa.Column('type', sa.Text(), nullable=True),
    sa.Column('value', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'checkpoint_id', 'task_id', 'idx'),
    if_not_exists=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('writes', if_exists=True)
    op.drop_table('checkpoints', if_exists=True)
    # ### end Alembic commands ###
